# Generated by Django 2.2.16 on 2022-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите аватар', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
